name: cloud-otp
version: '1.4.0'
summary: Cloud OTP
description: A versatile Open-Source One-Time Password (OTP) authenticator application built with Dart, supporting multiple platforms including Windows, Linux, Web, Android, iOS, and macOS.

grade: stable
confinement: strict
base: core22

parts:
  cloud-otp:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    stage-packages:
      - libgtk-3-0

apps:
  CloudOTP:
    command: build/linux/x64/release/bundle/cloud_otp
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11